# Generated by Django 2.2.3 on 2019-07-20 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('taskSubject', models.TextField(verbose_name='Текст задания')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель задания')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=50, verbose_name='Название организации')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель организации')),
                ('invitedUser', models.ManyToManyField(related_name='Сотрудники', to=settings.AUTH_USER_MODEL)),
                ('orgTasks', models.ManyToManyField(related_name='Задачи', to='Rest_Api.ToDoTask')),
            ],
        ),
    ]
