# Generated by Django 2.2.3 on 2019-07-20 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='todotask',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='orgTasks',
        ),
        migrations.AlterField(
            model_name='organization',
            name='invitedUser',
            field=models.ManyToManyField(related_name='invitedUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rest_Api.Organization', verbose_name='Организация'),
        ),
    ]
