# Generated by Django 2.2.3 on 2019-07-20 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rest_Api', '0002_auto_20190720_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='invitedUser',
        ),
        migrations.AddField(
            model_name='organization',
            name='invitedUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invitedUsers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
