# Generated by Django 2.2.3 on 2019-07-20 13:20

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_Api', '0004_auto_20190720_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='invitedUser',
            field=models.ManyToManyField(blank=True, default=django.contrib.auth.models.User, related_name='invitedUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
